### PR TITLE
Area+line

### PR DESCRIPTION
**Pull request by JosephBARBIERDARNAL**
#20

### CODE REVIEW

**Comment by dgkeyes** [comment]
@JosephBARBIERDARNAL thanks for this. Just a heads up, it may take me a few days to get to this, but I will soon.

**Comment by dgkeyes** [comment]
Ok @JosephBARBIERDARNAL I have some feedback for you on this: https://muse.ai/vt/F9gzHac

Let me know if you have any questions. And let me know when you have a new version for me to review. Thanks!

**Comment by JosephBARBIERDARNAL** [comment]
> Ok @JosephBARBIERDARNAL I have some feedback for you on this: https://muse.ai/vt/F9gzHac
> 
> Let me know if you have any questions. And let me know when you have a new version for me to review. Thanks!

Thanks for your feedback! I'll do it in the next few days

**Comment by JosephBARBIERDARNAL** [comment]
@dgkeyes I've made the requested changes to the blog post:

<br>

Screenshot 2024-09-22 at 13 16 37

**Comment by dgkeyes** [comment]
I messed up the PR, but I merged this one. Here's what I did: https://show.rfor.us/QvQLDYx4

I'm working on some things early this week, but let me get back to you about other posts later this week. Thanks!

**Comment by JosephBARBIERDARNAL** [comment]
Sounds good!

**Pull request merged**
