### PR TITLE
Post: custom ggplot2 theme (#18)

### PR DESCRIPTION
**Pull request by jadeynryan**

### CODE REVIEW

**Comment by dgkeyes** [comment]
Ok, just reviewed this. Here's some feedback: https://show.rfor.us/GXV0nMHN. Let me know if you have any questions. Thanks!

**Comment by jadeynryan** [comment]
@dgkeyes I think I addressed all your points! I did change the fuel economy plot back to a scatter plot with `geom_point` rather than `geom_line` since the relationship between mpg and weight isn't continuous.

Let me know if I'm good to record the video this weekend, or if more edits are needed. Thanks!

**Comment by dgkeyes** [comment]
Awesome! I just made a couple small changes:

- I renamed `nyt_theme()` to `theme_nyt()` to be consistent with typical theme names
- I separated out the code chunks that demonstrate code from the chunks that display the resulting plots to make things clearer

Feel free to record the video!

**Comment by jadeynryan** [comment]
Just finished the video! 

I'm not sure how to shorten the transition times between scenes (like the intro to where I show the NYT plot). I like how some of your other videos add annotations to code chunks so I verbally called out some line numbers where I thought it might be useful. Maybe Joe can help with these two things?

**Comment by dgkeyes** [comment]
Thanks, Jadey. We can definitely get Joe to help. I haven't had a chance to watch the video yet, but should later today or tomorrow. I'll get back to you then.

**Comment by dgkeyes** [comment]
Just watched the video. It looks good! I'm having Joe make a few small edits. Once he's done with that, I'll have you review and then we can get it scheduled.

**Pull request merged**
